// supabase.js
// Simple ES module wrapper for Supabase operations used by museum.html
// Usage:
//  1) Add meta tags to your HTML head:
//     <meta name="supabase-url" content="https://your-project.supabase.co">
//     <meta name="supabase-key" content="PUBLIC_ANON_KEY">
//  2) In museum.html (module script) call initSupabase({url, key}) or let museum.html read meta tags and call init automatically.
//  3) Call saveExhibit({ title, description, lat, lng }) to insert into the `exhibits` table.

import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

// Replace these constants with your actual Supabase project values.
// The user requested the keys be provided inside this JS file instead of via HTML meta tags.
const SUPABASE_URL = 'https://xqsntxaqjlmcugbvxzyw.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxc250eGFxamxtY3VnYnZ4enl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MjkwNzIsImV4cCI6MjA3NzIwNTA3Mn0.aR21j3hsr1di92zRbvSVM-Ud9hTSeoxhT5-ZDUv0GNk';

// Auto-initialize the Supabase client with the values above. If you need to override at runtime,
// call initSupabase({ url, key }) to reinitialize.
let supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

export function initSupabase({ url, key } = {}) {
  if (url && key) {
    supabase = createClient(url, key);
  }
  return supabase;
}

// Example DB table schema you should create in Supabase:
// create table public.exhibits (
//   id bigint generated by default as identity primary key,
//   title text,
//   description text,
//   lat double precision,
//   lng double precision,
//   created_at timestamptz default now()
// );

export async function saveExhibit({ title, description = '', lat, lng }) {
  if (!supabase) {
    return { error: new Error('Supabase not initialized'), data: null };
  }
  try {
    const payload = {
      title: title || null,
      description: description || null,
      lat: typeof lat === 'number' ? lat : Number(lat),
      lng: typeof lng === 'number' ? lng : Number(lng)
    };
    const { data, error } = await supabase
      .from('exhibits')
      .insert([payload])
      .select() // return inserted row if your DB allows
      .single();

    return { data, error };
  } catch (err) {
    return { error: err, data: null };
  }
}

export async function fetchExhibits() {
  if (!supabase) {
    return { error: new Error('Supabase not initialized'), data: null };
  }
  try {
    const { data, error } = await supabase.from('exhibits').select('*');
    return { data, error };
  } catch (err) {
    return { error: err, data: null };
  }
}

export async function deleteExhibit(id) {
  if (!supabase) {
    return { error: new Error('Supabase not initialized'), data: null };
  }
  if (id == null) return { error: new Error('id required'), data: null };
  try {
    const { data, error } = await supabase.from('exhibits').delete().eq('id', id);
    return { data, error };
  } catch (err) {
    return { error: err, data: null };
  }
}

// Reviews: simple functions to attach user reviews to exhibits
// Expected table schema:
// create table public.reviews (
//   id bigint generated by default as identity primary key,
//   exhibit_id bigint,
//   title text,
//   content text,
//   created_at timestamptz default now()
// );

export async function saveReview({ exhibit_id = null, title, content }) {
  if (!supabase) return { error: new Error('Supabase not initialized'), data: null };
  try {
    const payload = {
      exhibit_id: exhibit_id || null,
      title: title || null,
      content: content || null
    };
    const { data, error } = await supabase.from('reviews').insert([payload]).select().single();
    return { data, error };
  } catch (err) {
    return { error: err, data: null };
  }
}

export async function fetchReviews(exhibit_id) {
  if (!supabase) return { error: new Error('Supabase not initialized'), data: null };
  try {
    const query = supabase.from('reviews').select('*').order('created_at', { ascending: false });
    if (exhibit_id != null) query.eq('exhibit_id', exhibit_id);
    const { data, error } = await query;
    return { data, error };
  } catch (err) {
    return { error: err, data: null };
  }
}
